use eldenring::{
    param::CLEAR_COUNT_CORRECT_PARAM_ST,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ClearCountField {
    MaxHpRate,
    MaxMpRate,
    MaxStaminaRate,
    PhysicsAttackRate,
    SlashAttackRate,
    BlowAttackRate,
    ThrustAttackRate,
    NeturalAttackRate,
    MagicAttackRate,
    FireAttackRate,
    ThunderAttackRate,
    DarkAttackRate,
    PhysicsDefenseRate,
    MagicDefenseRate,
    FireDefenseRate,
    ThunderDefenseRate,
    DarkDefenseRate,
    StaminaAttackRate,
    SoulRate,
    PoisionResistRate,
    DiseaseResistRate,
    BloodResistRate,
    CurseResistRate,
    FreezeResistRate,
    BloodDamageRate,
    SuperArmorDamageRate,
    FreezeDamageRate,
    SleepResistRate,
    MadnessResistRate,
    SleepDamageRate,
    MadnessDamageRate,
}

impl ClearCountField {
    pub const ALL: [ClearCountField; 31] = [
        Self::MaxHpRate,
        Self::MaxMpRate,
        Self::MaxStaminaRate,
        Self::PhysicsAttackRate,
        Self::SlashAttackRate,
        Self::BlowAttackRate,
        Self::ThrustAttackRate,
        Self::NeturalAttackRate,
        Self::MagicAttackRate,
        Self::FireAttackRate,
        Self::ThunderAttackRate,
        Self::DarkAttackRate,
        Self::PhysicsDefenseRate,
        Self::MagicDefenseRate,
        Self::FireDefenseRate,
        Self::ThunderDefenseRate,
        Self::DarkDefenseRate,
        Self::StaminaAttackRate,
        Self::SoulRate,
        Self::PoisionResistRate,
        Self::DiseaseResistRate,
        Self::BloodResistRate,
        Self::CurseResistRate,
        Self::FreezeResistRate,
        Self::BloodDamageRate,
        Self::SuperArmorDamageRate,
        Self::FreezeDamageRate,
        Self::SleepResistRate,
        Self::MadnessResistRate,
        Self::SleepDamageRate,
        Self::MadnessDamageRate,
    ];
    #[allow(dead_code)]
    pub fn name(&self) -> &'static str {
        match self {
            ClearCountField::MaxHpRate => "max_hp_rate",
            ClearCountField::MaxMpRate => "max_mp_rate",
            ClearCountField::MaxStaminaRate => "max_stamina_rate",
            ClearCountField::PhysicsAttackRate => "physics_attack_rate",
            ClearCountField::SlashAttackRate => "slash_attack_rate",
            ClearCountField::BlowAttackRate => "blow_attack_rate",
            ClearCountField::ThrustAttackRate => "thrust_attack_rate",
            ClearCountField::NeturalAttackRate => "netural_attack_rate",
            ClearCountField::MagicAttackRate => "magic_attack_rate",
            ClearCountField::FireAttackRate => "fire_attack_rate",
            ClearCountField::ThunderAttackRate => "thunder_attack_rate",
            ClearCountField::DarkAttackRate => "dark_attack_rate",
            ClearCountField::PhysicsDefenseRate => "physics_defense_rate",
            ClearCountField::MagicDefenseRate => "magic_defense_rate",
            ClearCountField::FireDefenseRate => "fire_defense_rate",
            ClearCountField::ThunderDefenseRate => "thunder_defense_rate",
            ClearCountField::DarkDefenseRate => "dark_defense_rate",
            ClearCountField::StaminaAttackRate => "stamina_attack_rate",
            ClearCountField::SoulRate => "soul_rate",
            ClearCountField::PoisionResistRate => "poision_resist_rate",
            ClearCountField::DiseaseResistRate => "disease_resist_rate",
            ClearCountField::BloodResistRate => "blood_resist_rate",
            ClearCountField::CurseResistRate => "curse_resist_rate",
            ClearCountField::FreezeResistRate => "freeze_resist_rate",
            ClearCountField::BloodDamageRate => "blood_damage_rate",
            ClearCountField::SuperArmorDamageRate => "super_armor_damage_rate",
            ClearCountField::FreezeDamageRate => "freeze_damage_rate",
            ClearCountField::SleepResistRate => "sleep_resist_rate",
            ClearCountField::MadnessResistRate => "madness_resist_rate",
            ClearCountField::SleepDamageRate => "sleep_damage_rate",
            ClearCountField::MadnessDamageRate => "madness_damage_rate",
        }
    }
}

pub trait ClearCountFieldAccess {
    fn get_field(&self, field: ClearCountField) -> f32;
    fn set_field(&mut self, field: ClearCountField, value: f32);
}

impl ClearCountFieldAccess for CLEAR_COUNT_CORRECT_PARAM_ST {
    fn get_field(&self, field: ClearCountField) -> f32 {
        match field {
            ClearCountField::MaxHpRate => self.max_hp_rate(),
            ClearCountField::MaxMpRate => self.max_mp_rate(),
            ClearCountField::MaxStaminaRate => self.max_stamina_rate(),
            ClearCountField::PhysicsAttackRate => self.physics_attack_rate(),
            ClearCountField::SlashAttackRate => self.slash_attack_rate(),
            ClearCountField::BlowAttackRate => self.blow_attack_rate(),
            ClearCountField::ThrustAttackRate => self.thrust_attack_rate(),
            ClearCountField::NeturalAttackRate => self.netural_attack_rate(),
            ClearCountField::MagicAttackRate => self.magic_attack_rate(),
            ClearCountField::FireAttackRate => self.fire_attack_rate(),
            ClearCountField::ThunderAttackRate => self.thunder_attack_rate(),
            ClearCountField::DarkAttackRate => self.dark_attack_rate(),
            ClearCountField::PhysicsDefenseRate => self.physics_defense_rate(),
            ClearCountField::MagicDefenseRate => self.magic_defense_rate(),
            ClearCountField::FireDefenseRate => self.fire_defense_rate(),
            ClearCountField::ThunderDefenseRate => self.thunder_defense_rate(),
            ClearCountField::DarkDefenseRate => self.dark_defense_rate(),
            ClearCountField::StaminaAttackRate => self.stamina_attack_rate(),
            ClearCountField::SoulRate => self.soul_rate(),
            ClearCountField::PoisionResistRate => self.poision_resist_rate(),
            ClearCountField::DiseaseResistRate => self.disease_resist_rate(),
            ClearCountField::BloodResistRate => self.blood_resist_rate(),
            ClearCountField::CurseResistRate => self.curse_resist_rate(),
            ClearCountField::FreezeResistRate => self.freeze_resist_rate(),
            ClearCountField::BloodDamageRate => self.blood_damage_rate(),
            ClearCountField::SuperArmorDamageRate => self.super_armor_damage_rate(),
            ClearCountField::FreezeDamageRate => self.freeze_damage_rate(),
            ClearCountField::SleepResistRate => self.sleep_resist_rate(),
            ClearCountField::MadnessResistRate => self.madness_resist_rate(),
            ClearCountField::SleepDamageRate => self.sleep_damage_rate(),
            ClearCountField::MadnessDamageRate => self.madness_damage_rate(),
        }
    }

    fn set_field(&mut self, field: ClearCountField, value: f32) {
        match field {
            ClearCountField::MaxHpRate => self.set_max_hp_rate(value),
            ClearCountField::MaxMpRate => self.set_max_mp_rate(value),
            ClearCountField::MaxStaminaRate => self.set_max_stamina_rate(value),
            ClearCountField::PhysicsAttackRate => self.set_physics_attack_rate(value),
            ClearCountField::SlashAttackRate => self.set_slash_attack_rate(value),
            ClearCountField::BlowAttackRate => self.set_blow_attack_rate(value),
            ClearCountField::ThrustAttackRate => self.set_thrust_attack_rate(value),
            ClearCountField::NeturalAttackRate => self.set_netural_attack_rate(value),
            ClearCountField::MagicAttackRate => self.set_magic_attack_rate(value),
            ClearCountField::FireAttackRate => self.set_fire_attack_rate(value),
            ClearCountField::ThunderAttackRate => self.set_thunder_attack_rate(value),
            ClearCountField::DarkAttackRate => self.set_dark_attack_rate(value),
            ClearCountField::PhysicsDefenseRate => self.set_physics_defense_rate(value),
            ClearCountField::MagicDefenseRate => self.set_magic_defense_rate(value),
            ClearCountField::FireDefenseRate => self.set_fire_defense_rate(value),
            ClearCountField::ThunderDefenseRate => self.set_thunder_defense_rate(value),
            ClearCountField::DarkDefenseRate => self.set_dark_defense_rate(value),
            ClearCountField::StaminaAttackRate => self.set_stamina_attack_rate(value),
            ClearCountField::SoulRate => self.set_soul_rate(value),
            ClearCountField::PoisionResistRate => self.set_poision_resist_rate(value),
            ClearCountField::DiseaseResistRate => self.set_disease_resist_rate(value),
            ClearCountField::BloodResistRate => self.set_blood_resist_rate(value),
            ClearCountField::CurseResistRate => self.set_curse_resist_rate(value),
            ClearCountField::FreezeResistRate => self.set_freeze_resist_rate(value),
            ClearCountField::BloodDamageRate => self.set_blood_damage_rate(value),
            ClearCountField::SuperArmorDamageRate => self.set_super_armor_damage_rate(value),
            ClearCountField::FreezeDamageRate => self.set_freeze_damage_rate(value),
            ClearCountField::SleepResistRate => self.set_sleep_resist_rate(value),
            ClearCountField::MadnessResistRate => self.set_madness_resist_rate(value),
            ClearCountField::SleepDamageRate => self.set_sleep_damage_rate(value),
            ClearCountField::MadnessDamageRate => self.set_madness_damage_rate(value),
        }
    }
}