use eldenring::param::EQUIP_PARAM_GOODS_ST;
use std::sync::{Arc, OnceLock};
use std::collections::HashMap;
use winhook::HookHandle;

use crate::hook::*;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EquipParamGoodsField {
    DisableParamReserve2,
    RefIdDefault,
    SfxVariationId,
    Weight,
    BasicPrice,
    SellValue,
    BehaviorId,
    ReplaceItemId,
    SortId,
    AppearanceReplaceItemId,
    YesNoDialogMessageId,
    UseEnableSpEffectType,
    PotGroupId,
    IconId,
    ModelId,
    ShopLv,
    CompTrophySedId,
    TrophySeqId,
    MaxNum,
    ConsumeHeroPoint,
    OverDexterity,
    GoodsType,
    RefCategory,
    SpEffectCategory,
    QuickMatchUseRestriction,
    GoodsUseAnim,
    OpmeMenuType,
    UseLimitCategory,
    ReplaceCategory,
    Reserve4,
    SyncNumVaryId,
    RefId1,
    RefVirtualWepId,
    VagrantItemLotId,
    VagrantBonusEneDropItemLotId,
    VagrantItemEneDropItemLotId,
    CastSfxId,
    FireSfxId,
    EffectSfxId,
    SuppleType,
    AutoReplenishType,
    MaxRepositoryNum,
    SortGroupId,
    SaleValue,
    Rarity,
    UseLimitSummonBuddy,
    UseLimitSpEffectType,
    AiUseJudgeId,
    ConsumeMp,
    ConsumeHp,
    ReinforceGoodsId,
    ReinforceMaterialId,
    ReinforcePrice,
    UseLevelVowType0,
    UseLevelVowType1,
    UseLevelVowType2,
    UseLevelVowType3,
    UseLevelVowType4,
    UseLevelVowType5,
    UseLevelVowType6,
    UseLevelVowType7,
    UseLevelVowType8,
    UseLevelVowType9,
    UseLevelVowType10,
    UseLevelVowType11,
    UseLevelVowType12,
    UseLevelVowType13,
    UseLevelVowType14,
    UseLevelVowType15,
    UseLevel,
    Reserve5,
    ItemGetTutorialFlagId,
    Reserve3,
}

impl EquipParamGoodsField {
    pub const ALL: [EquipParamGoodsField; 73] = [
        Self::DisableParamReserve2,
        Self::RefIdDefault,
        Self::SfxVariationId,
        Self::Weight,
        Self::BasicPrice,
        Self::SellValue,
        Self::BehaviorId,
        Self::ReplaceItemId,
        Self::SortId,
        Self::AppearanceReplaceItemId,
        Self::YesNoDialogMessageId,
        Self::UseEnableSpEffectType,
        Self::PotGroupId,
        Self::IconId,
        Self::ModelId,
        Self::ShopLv,
        Self::CompTrophySedId,
        Self::TrophySeqId,
        Self::MaxNum,
        Self::ConsumeHeroPoint,
        Self::OverDexterity,
        Self::GoodsType,
        Self::RefCategory,
        Self::SpEffectCategory,
        Self::QuickMatchUseRestriction,
        Self::GoodsUseAnim,
        Self::OpmeMenuType,
        Self::UseLimitCategory,
        Self::ReplaceCategory,
        Self::Reserve4,
        Self::SyncNumVaryId,
        Self::RefId1,
        Self::RefVirtualWepId,
        Self::VagrantItemLotId,
        Self::VagrantBonusEneDropItemLotId,
        Self::VagrantItemEneDropItemLotId,
        Self::CastSfxId,
        Self::FireSfxId,
        Self::EffectSfxId,
        Self::SuppleType,
        Self::AutoReplenishType,
        Self::MaxRepositoryNum,
        Self::SortGroupId,
        Self::SaleValue,
        Self::Rarity,
        Self::UseLimitSummonBuddy,
        Self::UseLimitSpEffectType,
        Self::AiUseJudgeId,
        Self::ConsumeMp,
        Self::ConsumeHp,
        Self::ReinforceGoodsId,
        Self::ReinforceMaterialId,
        Self::ReinforcePrice,
        Self::UseLevelVowType0,
        Self::UseLevelVowType1,
        Self::UseLevelVowType2,
        Self::UseLevelVowType3,
        Self::UseLevelVowType4,
        Self::UseLevelVowType5,
        Self::UseLevelVowType6,
        Self::UseLevelVowType7,
        Self::UseLevelVowType8,
        Self::UseLevelVowType9,
        Self::UseLevelVowType10,
        Self::UseLevelVowType11,
        Self::UseLevelVowType12,
        Self::UseLevelVowType13,
        Self::UseLevelVowType14,
        Self::UseLevelVowType15,
        Self::UseLevel,
        Self::Reserve5,
        Self::ItemGetTutorialFlagId,
        Self::Reserve3,
    ];

    #[allow(dead_code)]
    pub fn name(&self) -> &'static str {
        match self {
            EquipParamGoodsField::DisableParamReserve2 => "disable_param_reserve2",
            EquipParamGoodsField::RefIdDefault => "ref_id_default",
            EquipParamGoodsField::SfxVariationId => "sfx_variation_id",
            EquipParamGoodsField::Weight => "weight",
            EquipParamGoodsField::BasicPrice => "basic_price",
            EquipParamGoodsField::SellValue => "sell_value",
            EquipParamGoodsField::BehaviorId => "behavior_id",
            EquipParamGoodsField::ReplaceItemId => "replace_item_id",
            EquipParamGoodsField::SortId => "sort_id",
            EquipParamGoodsField::AppearanceReplaceItemId => "appearance_replace_item_id",
            EquipParamGoodsField::YesNoDialogMessageId => "yes_no_dialog_message_id",
            EquipParamGoodsField::UseEnableSpEffectType => "use_enable_sp_effect_type",
            EquipParamGoodsField::PotGroupId => "pot_group_id",
            EquipParamGoodsField::IconId => "icon_id",
            EquipParamGoodsField::ModelId => "model_id",
            EquipParamGoodsField::ShopLv => "shop_lv",
            EquipParamGoodsField::CompTrophySedId => "comp_trophy_sed_id",
            EquipParamGoodsField::TrophySeqId => "trophy_seq_id",
            EquipParamGoodsField::MaxNum => "max_num",
            EquipParamGoodsField::ConsumeHeroPoint => "consume_hero_point",
            EquipParamGoodsField::OverDexterity => "over_dexterity",
            EquipParamGoodsField::GoodsType => "goods_type",
            EquipParamGoodsField::RefCategory => "ref_category",
            EquipParamGoodsField::SpEffectCategory => "sp_effect_category",
            EquipParamGoodsField::QuickMatchUseRestriction => "quick_match_use_restriction",
            EquipParamGoodsField::GoodsUseAnim => "goods_use_anim",
            EquipParamGoodsField::OpmeMenuType => "opme_menu_type",
            EquipParamGoodsField::UseLimitCategory => "use_limit_category",
            EquipParamGoodsField::ReplaceCategory => "replace_category",
            EquipParamGoodsField::Reserve4 => "reserve4",
            EquipParamGoodsField::SyncNumVaryId => "sync_num_vary_id",
            EquipParamGoodsField::RefId1 => "ref_id_1",
            EquipParamGoodsField::RefVirtualWepId => "ref_virtual_wep_id",
            EquipParamGoodsField::VagrantItemLotId => "vagrant_item_lot_id",
            EquipParamGoodsField::VagrantBonusEneDropItemLotId => "vagrant_bonus_ene_drop_item_lot_id",
            EquipParamGoodsField::VagrantItemEneDropItemLotId => "vagrant_item_ene_drop_item_lot_id",
            EquipParamGoodsField::CastSfxId => "cast_sfx_id",
            EquipParamGoodsField::FireSfxId => "fire_sfx_id",
            EquipParamGoodsField::EffectSfxId => "effect_sfx_id",
            EquipParamGoodsField::SuppleType => "supple_type",
            EquipParamGoodsField::AutoReplenishType => "auto_replenish_type",
            EquipParamGoodsField::MaxRepositoryNum => "max_repository_num",
            EquipParamGoodsField::SortGroupId => "sort_group_id",
            EquipParamGoodsField::SaleValue => "sale_value",
            EquipParamGoodsField::Rarity => "rarity",
            EquipParamGoodsField::UseLimitSummonBuddy => "use_limit_summon_buddy",
            EquipParamGoodsField::UseLimitSpEffectType => "use_limit_sp_effect_type",
            EquipParamGoodsField::AiUseJudgeId => "ai_use_judge_id",
            EquipParamGoodsField::ConsumeMp => "consume_mp",
            EquipParamGoodsField::ConsumeHp => "consume_hp",
            EquipParamGoodsField::ReinforceGoodsId => "reinforce_goods_id",
            EquipParamGoodsField::ReinforceMaterialId => "reinforce_material_id",
            EquipParamGoodsField::ReinforcePrice => "reinforce_price",
            EquipParamGoodsField::UseLevelVowType0 => "use_level_vow_type0",
            EquipParamGoodsField::UseLevelVowType1 => "use_level_vow_type1",
            EquipParamGoodsField::UseLevelVowType2 => "use_level_vow_type2",
            EquipParamGoodsField::UseLevelVowType3 => "use_level_vow_type3",
            EquipParamGoodsField::UseLevelVowType4 => "use_level_vow_type4",
            EquipParamGoodsField::UseLevelVowType5 => "use_level_vow_type5",
            EquipParamGoodsField::UseLevelVowType6 => "use_level_vow_type6",
            EquipParamGoodsField::UseLevelVowType7 => "use_level_vow_type7",
            EquipParamGoodsField::UseLevelVowType8 => "use_level_vow_type8",
            EquipParamGoodsField::UseLevelVowType9 => "use_level_vow_type9",
            EquipParamGoodsField::UseLevelVowType10 => "use_level_vow_type10",
            EquipParamGoodsField::UseLevelVowType11 => "use_level_vow_type11",
            EquipParamGoodsField::UseLevelVowType12 => "use_level_vow_type12",
            EquipParamGoodsField::UseLevelVowType13 => "use_level_vow_type13",
            EquipParamGoodsField::UseLevelVowType14 => "use_level_vow_type14",
            EquipParamGoodsField::UseLevelVowType15 => "use_level_vow_type15",
            EquipParamGoodsField::UseLevel => "use_level",
            EquipParamGoodsField::Reserve5 => "reserve5",
            EquipParamGoodsField::ItemGetTutorialFlagId => "item_get_tutorial_flag_id",
            EquipParamGoodsField::Reserve3 => "reserve3",
        }
    }
}

pub trait EquipParamGoodsFieldAccess {
    fn get_field(&self, field: EquipParamGoodsField) -> f32;
    fn set_field(&mut self, field: EquipParamGoodsField, value: f32);
}

impl EquipParamGoodsFieldAccess for EQUIP_PARAM_GOODS_ST {
     fn get_field(&self, field: EquipParamGoodsField) -> f32 {
        match field {
            EquipParamGoodsField::DisableParamReserve2 => unimplemented!("Array field"),
            EquipParamGoodsField::RefIdDefault => self.ref_id_default() as f32,
            EquipParamGoodsField::SfxVariationId => self.sfx_variation_id() as f32,
            EquipParamGoodsField::Weight => self.weight(),
            EquipParamGoodsField::BasicPrice => self.basic_price() as f32,
            EquipParamGoodsField::SellValue => self.sell_value() as f32,
            EquipParamGoodsField::BehaviorId => self.behavior_id() as f32,
            EquipParamGoodsField::ReplaceItemId => self.replace_item_id() as f32,
            EquipParamGoodsField::SortId => self.sort_id() as f32,
            EquipParamGoodsField::AppearanceReplaceItemId => self.appearance_replace_item_id() as f32,
            EquipParamGoodsField::YesNoDialogMessageId => self.yes_no_dialog_message_id() as f32,
            EquipParamGoodsField::UseEnableSpEffectType => self.use_enable_sp_effect_type() as f32,
            EquipParamGoodsField::PotGroupId => self.pot_group_id() as f32,
            EquipParamGoodsField::IconId => self.icon_id() as f32,
            EquipParamGoodsField::ModelId => self.model_id() as f32,
            EquipParamGoodsField::ShopLv => self.shop_lv() as f32,
            EquipParamGoodsField::CompTrophySedId => self.comp_trophy_sed_id() as f32,
            EquipParamGoodsField::TrophySeqId => self.trophy_seq_id() as f32,
            EquipParamGoodsField::MaxNum => self.max_num() as f32,
            EquipParamGoodsField::ConsumeHeroPoint => self.consume_hero_point() as f32,
            EquipParamGoodsField::OverDexterity => self.over_dexterity() as f32,
            EquipParamGoodsField::GoodsType => self.goods_type() as f32,
            EquipParamGoodsField::RefCategory => self.ref_category() as f32,
            EquipParamGoodsField::SpEffectCategory => self.sp_effect_category() as f32,
            EquipParamGoodsField::QuickMatchUseRestriction => self.quick_match_use_restriction() as f32,
            EquipParamGoodsField::GoodsUseAnim => self.goods_use_anim() as f32,
            EquipParamGoodsField::OpmeMenuType => self.opme_menu_type() as f32,
            EquipParamGoodsField::UseLimitCategory => self.use_limit_category() as f32,
            EquipParamGoodsField::ReplaceCategory => self.replace_category() as f32,
            EquipParamGoodsField::Reserve4 => unimplemented!("Array field"),
            EquipParamGoodsField::SyncNumVaryId => self.sync_num_vary_id() as f32,
            EquipParamGoodsField::RefId1 => self.ref_id_1() as f32,
            EquipParamGoodsField::RefVirtualWepId => self.ref_virtual_wep_id() as f32,
            EquipParamGoodsField::VagrantItemLotId => self.vagrant_item_lot_id() as f32,
            EquipParamGoodsField::VagrantBonusEneDropItemLotId => self.vagrant_bonus_ene_drop_item_lot_id() as f32,
            EquipParamGoodsField::VagrantItemEneDropItemLotId => self.vagrant_item_ene_drop_item_lot_id() as f32,
            EquipParamGoodsField::CastSfxId => self.cast_sfx_id() as f32,
            EquipParamGoodsField::FireSfxId => self.fire_sfx_id() as f32,
            EquipParamGoodsField::EffectSfxId => self.effect_sfx_id() as f32,
            EquipParamGoodsField::SuppleType => self.supple_type() as f32,
            EquipParamGoodsField::AutoReplenishType => self.auto_replenish_type() as f32,
            EquipParamGoodsField::MaxRepositoryNum => self.max_repository_num() as f32,
            EquipParamGoodsField::SortGroupId => self.sort_group_id() as f32,
            EquipParamGoodsField::SaleValue => self.sale_value() as f32,
            EquipParamGoodsField::Rarity => self.rarity() as f32,
            EquipParamGoodsField::UseLimitSummonBuddy => self.use_limit_summon_buddy() as f32,
            EquipParamGoodsField::UseLimitSpEffectType => self.use_limit_sp_effect_type() as f32,
            EquipParamGoodsField::AiUseJudgeId => self.ai_use_judge_id() as f32,
            EquipParamGoodsField::ConsumeMp => self.consume_mp() as f32,
            EquipParamGoodsField::ConsumeHp => self.consume_hp() as f32,
            EquipParamGoodsField::ReinforceGoodsId => self.reinforce_goods_id() as f32,
            EquipParamGoodsField::ReinforceMaterialId => self.reinforce_material_id() as f32,
            EquipParamGoodsField::ReinforcePrice => self.reinforce_price() as f32,
            EquipParamGoodsField::UseLevelVowType0 => self.use_level_vow_type0() as f32,
            EquipParamGoodsField::UseLevelVowType1 => self.use_level_vow_type1() as f32,
            EquipParamGoodsField::UseLevelVowType2 => self.use_level_vow_type2() as f32,
            EquipParamGoodsField::UseLevelVowType3 => self.use_level_vow_type3() as f32,
            EquipParamGoodsField::UseLevelVowType4 => self.use_level_vow_type4() as f32,
            EquipParamGoodsField::UseLevelVowType5 => self.use_level_vow_type5() as f32,
            EquipParamGoodsField::UseLevelVowType6 => self.use_level_vow_type6() as f32,
            EquipParamGoodsField::UseLevelVowType7 => self.use_level_vow_type7() as f32,
            EquipParamGoodsField::UseLevelVowType8 => self.use_level_vow_type8() as f32,
            EquipParamGoodsField::UseLevelVowType9 => self.use_level_vow_type9() as f32,
            EquipParamGoodsField::UseLevelVowType10 => self.use_level_vow_type10() as f32,
            EquipParamGoodsField::UseLevelVowType11 => self.use_level_vow_type11() as f32,
            EquipParamGoodsField::UseLevelVowType12 => self.use_level_vow_type12() as f32,
            EquipParamGoodsField::UseLevelVowType13 => self.use_level_vow_type13() as f32,
            EquipParamGoodsField::UseLevelVowType14 => self.use_level_vow_type14() as f32,
            EquipParamGoodsField::UseLevelVowType15 => self.use_level_vow_type15() as f32,
            EquipParamGoodsField::UseLevel => self.use_level() as f32,
            EquipParamGoodsField::Reserve5 => unimplemented!("Array field"),
            EquipParamGoodsField::ItemGetTutorialFlagId => self.item_get_tutorial_flag_id() as f32,
            EquipParamGoodsField::Reserve3 => unimplemented!("Array field"),
        }
    }

    fn set_field(&mut self, field: EquipParamGoodsField, value: f32) {
        match field {
            EquipParamGoodsField::DisableParamReserve2 => unimplemented!("Array field"),
            EquipParamGoodsField::RefIdDefault => self.set_ref_id_default(value as i32),
            EquipParamGoodsField::SfxVariationId => self.set_sfx_variation_id(value as i32),
            EquipParamGoodsField::Weight => self.set_weight(value),
            EquipParamGoodsField::BasicPrice => self.set_basic_price(value as i32),
            EquipParamGoodsField::SellValue => self.set_sell_value(value as i32),
            EquipParamGoodsField::BehaviorId => self.set_behavior_id(value as i32),
            EquipParamGoodsField::ReplaceItemId => self.set_replace_item_id(value as i32),
            EquipParamGoodsField::SortId => self.set_sort_id(value as i32),
            EquipParamGoodsField::AppearanceReplaceItemId => self.set_appearance_replace_item_id(value as i32),
            EquipParamGoodsField::YesNoDialogMessageId => self.set_yes_no_dialog_message_id(value as i32),
            EquipParamGoodsField::UseEnableSpEffectType => self.set_use_enable_sp_effect_type(value as u16),
            EquipParamGoodsField::PotGroupId => self.set_pot_group_id(value as i8),
            EquipParamGoodsField::IconId => self.set_icon_id(value as u16),
            EquipParamGoodsField::ModelId => self.set_model_id(value as u16),
            EquipParamGoodsField::ShopLv => self.set_shop_lv(value as i16),
            EquipParamGoodsField::CompTrophySedId => self.set_comp_trophy_sed_id(value as i16),
            EquipParamGoodsField::TrophySeqId => self.set_trophy_seq_id(value as i16),
            EquipParamGoodsField::MaxNum => self.set_max_num(value as i16),
            EquipParamGoodsField::ConsumeHeroPoint => self.set_consume_hero_point(value as u8),
            EquipParamGoodsField::OverDexterity => self.set_over_dexterity(value as u8),
            EquipParamGoodsField::GoodsType => self.set_goods_type(value as u8),
            EquipParamGoodsField::RefCategory => self.set_ref_category(value as u8),
            EquipParamGoodsField::SpEffectCategory => self.set_sp_effect_category(value as u8),
            EquipParamGoodsField::QuickMatchUseRestriction => self.set_quick_match_use_restriction(value as u8),
            EquipParamGoodsField::GoodsUseAnim => self.set_goods_use_anim(value as u8),
            EquipParamGoodsField::OpmeMenuType => self.set_opme_menu_type(value as u8),
            EquipParamGoodsField::UseLimitCategory => self.set_use_limit_category(value as u8),
            EquipParamGoodsField::ReplaceCategory => self.set_replace_category(value as u8),
            EquipParamGoodsField::Reserve4 => unimplemented!("Array field"),
            EquipParamGoodsField::SyncNumVaryId => self.set_sync_num_vary_id(value as u8),
            EquipParamGoodsField::RefId1 => self.set_ref_id_1(value as i32),
            EquipParamGoodsField::RefVirtualWepId => self.set_ref_virtual_wep_id(value as i32),
            EquipParamGoodsField::VagrantItemLotId => self.set_vagrant_item_lot_id(value as i32),
            EquipParamGoodsField::VagrantBonusEneDropItemLotId => self.set_vagrant_bonus_ene_drop_item_lot_id(value as i32),
            EquipParamGoodsField::VagrantItemEneDropItemLotId => self.set_vagrant_item_ene_drop_item_lot_id(value as i32),
            EquipParamGoodsField::CastSfxId => self.set_cast_sfx_id(value as i32),
            EquipParamGoodsField::FireSfxId => self.set_fire_sfx_id(value as i32),
            EquipParamGoodsField::EffectSfxId => self.set_effect_sfx_id(value as i32),
            EquipParamGoodsField::SuppleType => self.set_supple_type(value as u8),
            EquipParamGoodsField::AutoReplenishType => self.set_auto_replenish_type(value as u8),
            EquipParamGoodsField::MaxRepositoryNum => self.set_max_repository_num(value as i16),
            EquipParamGoodsField::SortGroupId => self.set_sort_group_id(value as u8),
            EquipParamGoodsField::SaleValue => self.set_sale_value(value as i32),
            EquipParamGoodsField::Rarity => self.set_rarity(value as u8),
            EquipParamGoodsField::UseLimitSummonBuddy => self.set_use_limit_summon_buddy(value as u8),
            EquipParamGoodsField::UseLimitSpEffectType => self.set_use_limit_sp_effect_type(value as u16),
            EquipParamGoodsField::AiUseJudgeId => self.set_ai_use_judge_id(value as i32),
            EquipParamGoodsField::ConsumeMp => self.set_consume_mp(value as i16),
            EquipParamGoodsField::ConsumeHp => self.set_consume_hp(value as i16),
            EquipParamGoodsField::ReinforceGoodsId => self.set_reinforce_goods_id(value as i32),
            EquipParamGoodsField::ReinforceMaterialId => self.set_reinforce_material_id(value as i32),
            EquipParamGoodsField::ReinforcePrice => self.set_reinforce_price(value as i32),
            EquipParamGoodsField::UseLevelVowType0 => self.set_use_level_vow_type0(value as i8),
            EquipParamGoodsField::UseLevelVowType1 => self.set_use_level_vow_type1(value as i8),
            EquipParamGoodsField::UseLevelVowType2 => self.set_use_level_vow_type2(value as i8),
            EquipParamGoodsField::UseLevelVowType3 => self.set_use_level_vow_type3(value as i8),
            EquipParamGoodsField::UseLevelVowType4 => self.set_use_level_vow_type4(value as i8),
            EquipParamGoodsField::UseLevelVowType5 => self.set_use_level_vow_type5(value as i8),
            EquipParamGoodsField::UseLevelVowType6 => self.set_use_level_vow_type6(value as i8),
            EquipParamGoodsField::UseLevelVowType7 => self.set_use_level_vow_type7(value as i8),
            EquipParamGoodsField::UseLevelVowType8 => self.set_use_level_vow_type8(value as i8),
            EquipParamGoodsField::UseLevelVowType9 => self.set_use_level_vow_type9(value as i8),
            EquipParamGoodsField::UseLevelVowType10 => self.set_use_level_vow_type10(value as i8),
            EquipParamGoodsField::UseLevelVowType11 => self.set_use_level_vow_type11(value as i8),
            EquipParamGoodsField::UseLevelVowType12 => self.set_use_level_vow_type12(value as i8),
            EquipParamGoodsField::UseLevelVowType13 => self.set_use_level_vow_type13(value as i8),
            EquipParamGoodsField::UseLevelVowType14 => self.set_use_level_vow_type14(value as i8),
            EquipParamGoodsField::UseLevelVowType15 => self.set_use_level_vow_type15(value as i8),
            EquipParamGoodsField::UseLevel => self.set_use_level(value as u16),
            EquipParamGoodsField::Reserve5 => unimplemented!("Array field"),
            EquipParamGoodsField::ItemGetTutorialFlagId => self.set_item_get_tutorial_flag_id(value as u32),
            EquipParamGoodsField::Reserve3 => unimplemented!("Array field"),
        }
    }
}

pub const GET_GOODS_AOB: &str = "8b 12 48 8d 4d c0 83 cf ff 89 75 c4 89 7d c0 48 89 75 c8 e8 ? ? ? ? 48 8b 45 c8 48 85 c0 74 03 8b 78 74 8b c7 eb 32";
pub const GET_GOODS_OFFSET: usize = 20;

#[repr(C, packed)]
pub struct GetGoodsResult {
    pub id: u32,
    pub _1: [u8; 0x4],
    pub row: *mut EQUIP_PARAM_GOODS_ST,
}

pub type GetGoodsType = unsafe extern "C" fn(
    result: *mut GetGoodsResult,
    id: u32,
);

pub static GET_GOODS_ORIGINAL_HOLDER: OnceLock<GetGoodsType> = OnceLock::new();