[workspace]
resolver = "3"
members = ["mods/endlessNg"]

[workspace.dependencies]
eldenring = { git = "https://github.com/vswarte/fromsoftware-rs", version = "0.12.0" }
fromsoftware-shared = { git = "https://github.com/vswarte/fromsoftware-rs", version = "0.12.0" }
windows = {version =  "0.62.2", features=["Win32_UI_Input_XboxController"]}
