[package]
name = "rally_mod"
version = "0.1.0"
edition = "2024"

[dependencies]
utils = { path = "../../utils" }
fromsoftware-shared.workspace = true
eldenring.workspace = true
windows.workspace = true
windows-sys.workspace = true
pelite.workspace = true
winhook.workspace = true
closure-ffi.workspace = true
toml_edit.workspace = true

[lib]
crate-type = ["cdylib"]
